### ISSUE TITLE
cilium status --wait panics with concurrent map access

### ISSUE THREAD

**Issue by squeed** [cilium/cilium-cli#1761]
I saw a test failure in a [CI run](https://github.com/cilium/cilium/actions/runs/5357011312/jobs/9717274930?pr=26242) where `cilium status --wait` panicked:

```
fatal error: concurrent map read and map write

goroutine 16 [running]:
k8s.io/apimachinery/pkg/runtime.(*Scheme).ObjectKinds(0xc0004e72d0, {0x38c0aa0?, 0xc00093eea0})
	/cilium/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:267 +0x1ca
k8s.io/apimachinery/pkg/runtime.(*parameterCodec).EncodeParameters(0xc00039d9c0, {0x38c0aa0, 0xc00093eea0}, {{0x0, 0x0}, {0x2bd68a2, 0x2}})
	/cilium/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:191 +0x6e
k8s.io/client-go/rest.(*Request).SpecificallyVersionedParams(0xc000944d80, {0x38c0aa0?, 0xc00093eea0?}, {0x38c0dc0?, 0xc00039d9c0?}, {{0x0?, 0x2b93f60?}, {0x2bd68a2?, 0xc00094f648?}})
	/cilium/vendor/k8s.io/client-go/rest/request.go:376 +0x83
k8s.io/client-go/rest.(*Request).VersionedParams(...)
	/cilium/vendor/k8s.io/client-go/rest/request.go:369
k8s.io/client-go/kubernetes/typed/core/v1.(*pods).List(0xc0005ac3a0, {0x38d78e0, 0xc0007a5ec0}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x2c1e2a1, 0x14}, {0x0, ...}, ...})
	/cilium/vendor/k8s.io/client-go/kubernetes/typed/core/v1/pod.go:97 +0x145
github.com/cilium/cilium-cli/k8s.(*Client).ListPods(0xc00039a210?, {0x38d78e0, 0xc0007a5ec0}, {0x2bf3a2b, 0xb}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x2c1e2a1, ...}, ...})
	/cilium/k8s/client.go:347 +0xac
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).podStatus(0x27c9da0?, {0x38d78e0, 0xc0007a5ec0}, 0xc0002952d0, {0x2c033e4, 0xf}, {0x2c1e2a1?, 0x0?}, 0x0)
	/cilium/status/k8s.go:270 +0xa8
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).status.func3({0x0?, 0x0?})
	/cilium/status/k8s.go:428 +0x4c7
github.com/cilium/workerpool.(*WorkerPool).run.func1()
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:181 +0x82
created by github.com/cilium/workerpool.(*WorkerPool).run
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:178 +0x4e

...

goroutine 66 [runnable]:
k8s.io/apimachinery/pkg/runtime.(*Scheme).AddUnversionedTypes(0xc0004e72d0, {{0x0?, 0x14?}, {0x2bd68a2?, 0xa?}}, {0xc00092cc00?, 0x5, 0x5?})
	/cilium/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:128 +0x20f
k8s.io/apimachinery/pkg/apis/meta/v1.AddToGroupVersion(0xc0004e72d0?, {{0x2c1c84d?, 0x0?}, {0x2bd68a2?, 0x0?}})
	/cilium/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/register.go:75 +0x339
k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1.addKnownTypes(0x0?)
	/cilium/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/register.go:53 +0x105
k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(...)
	/cilium/vendor/k8s.io/apimachinery/pkg/runtime/scheme_builder.go:29
helm.sh/helm/v3/pkg/kube.New.func1()
	/cilium/vendor/helm.sh/helm/v3/pkg/kube/client.go:89 +0x27
sync.(*Once).doSlow(0x38d78e0?, 0x0?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
helm.sh/helm/v3/pkg/kube.New({0x38d8bb0?, 0xc0008b0c60?})
	/cilium/vendor/helm.sh/helm/v3/pkg/kube/client.go:88 +0x65
helm.sh/helm/v3/pkg/action.(*Configuration).Init(0xc00092cef8, {0x38d8bb0?, 0xc0008b0c60}, {0x2bf3a2b, 0xb}, {0x0, 0x0}, 0x3607588)
	/cilium/vendor/helm.sh/helm/v3/pkg/action/action.go:372 +0x79
github.com/cilium/cilium-cli/internal/helm.Get({0x38d8bb0?, 0xc0008b0c60?}, {{0x2bf3a2b?, 0x0?}, {0x2bdd8b9?, 0x0?}})
	/cilium/internal/helm/helm.go:577 +0x9d
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).status.func8({0xc0004f0000?, 0xc0003dc200?})
	/cilium/status/k8s.go:548 +0x65
github.com/cilium/workerpool.(*WorkerPool).run.func1()
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:181 +0x82
created by github.com/cilium/workerpool.(*WorkerPool).run
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:178 +0x4e
```

**Comment by michi-covalent** [comment]
i'm working on fixing this. let's use #1794 for tracking ✅
