### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by bimmlerd** [cilium/cilium-cli#1794]
## Bug report

**General Information**

- Cilium CLI version `v0.14.8`
- Link to relevant artifacts: Failing `cilium/cilium` CI log: https://github.com/cilium/cilium/actions/runs/5445428489/jobs/9904687913#step:17:23. Sysdumps, the relevant failing test is nr 10, `
Installation and Connectivity Test (10, vxlan, dual, wireguard, iptables, false, cluster, cluster) `. [cilium-sysdumps.zip](https://github.com/cilium/cilium-cli/files/11937930/cilium-sysdumps.zip)
 

**How to reproduce the issue**

Unclear. CI seems to have been running `cilium --context kind-cluster1-5445428489 status --wait`. , it seems that deep in the K8s Client guts we read and write a `(*Scheme).unversionedTypes` map concurrently. The helm part of the stack trace looks like we hit some helm lazy initialisation path. Here's the stack trace:

```
fatal error: concurrent map read and map write

goroutine 28 [running]:
k8s.io/apimachinery/pkg/runtime.(*Scheme).ObjectKinds(0xc0003ace00, {0x39c1270?, 0xc0005fac60})
	/cilium/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:267 +0x1ca
k8s.io/apimachinery/pkg/runtime.(*parameterCodec).EncodeParameters(0xc0000f3840, {0x39c1270, 0xc0005fac60}, {{0x0, 0x0}, {0x2c54cf2, 0x2}})
	/cilium/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:191 +0x6e
k8s.io/client-go/rest.(*Request).SpecificallyVersionedParams(0xc00059de60, {0x39c1270?, 0xc0005fac60?}, {0x39c1590?, 0xc0000f3840?}, {{0x0?, 0x2c11f00?}, {0x2c54cf2?, 0xc0000f9608?}})
	/cilium/vendor/k8s.io/client-go/rest/request.go:376 +0x83
k8s.io/client-go/rest.(*Request).VersionedParams(...)
	/cilium/vendor/k8s.io/client-go/rest/request.go:369
k8s.io/client-go/kubernetes/typed/core/v1.(*pods).List(0xc000431120, {0x39d8100, 0xc0002c62d0}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x2c9c4cc, 0x14}, {0x0, ...}, ...})
	/cilium/vendor/k8s.io/client-go/kubernetes/typed/core/v1/pod.go:97 +0x145
github.com/cilium/cilium-cli/k8s.(*Client).ListPods(0xc0005f8160?, {0x39d8100, 0xc0002c62d0}, {0x2c71f81, 0xb}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x2c9c4cc, ...}, ...})
	/cilium/k8s/client.go:347 +0xac
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).podStatus(0x2834760?, {0x39d8100, 0xc0002c62d0}, 0xc000b2cfc0, {0x2c75d6c, 0xc}, {0x2c9c4cc?, 0xc0004ead8e?}, 0x0)
	/cilium/status/k8s.go:270 +0xa8
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).status.func4({0xc0006fa600?, 0xc000410b00?})
	/cilium/status/k8s.go:452 +0x72a
github.com/cilium/workerpool.(*WorkerPool).run.func1()
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:181 +0x82
created by github.com/cilium/workerpool.(*WorkerPool).run
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:178 +0x4e

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x405d9d?)
	/usr/local/go/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc000a13980?)
	/usr/local/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000225c00, {0x39b1360?, 0xc00011a030}, 0x5500?)
	/usr/local/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc000225c00, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc000225c00, {0xc000358000, 0x1000, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:1316 +0x16f
bufio.(*Reader).Read(0xc0004f38c0, {0xc0000f4200, 0x9, 0xc0006fac88?})
	/usr/local/go/src/bufio/bufio.go:237 +0x1bb
io.ReadAtLeast({0x39a2260, 0xc0004f38c0}, {0xc0000f4200, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:351
golang.org/x/net/http2.readFrameHeader({0xc0000f4200?, 0x9?, 0xc001614f00?}, {0x39a2260?, 0xc0004f38c0?})
	/cilium/vendor/golang.org/x/net/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0000f41c0)
	/cilium/vendor/golang.org/x/net/http2/frame.go:498 +0x95
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000b48f98)
	/cilium/vendor/golang.org/x/net/http2/transport.go:2260 +0x12e
golang.org/x/net/http2.(*ClientConn).readLoop(0xc0006fa180)
	/cilium/vendor/golang.org/x/net/http2/transport.go:2155 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/cilium/vendor/golang.org/x/net/http2/transport.go:818 +0xc1f

goroutine 14 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x78?, 0x15cc5d0?)
	/usr/local/go/src/runtime/sema.go:77 +0x26
sync.(*Mutex).lockSlow(0xc0003efa50)
	/usr/local/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:90
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).deploymentStatus(0x0?, {0x39d8100?, 0xc0002c62d0?}, 0xc000b2cfc0, {0x2c9ff0a, 0x15})
	/cilium/status/k8s.go:161 +0x196
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).status.func6({0xc000217680?, 0xc0006d7300?})
	/cilium/status/k8s.go:497 +0x7c
github.com/cilium/workerpool.(*WorkerPool).run.func1()
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:181 +0x82
created by github.com/cilium/workerpool.(*WorkerPool).run
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:178 +0x4e

goroutine 33 [select]:
golang.org/x/net/http2.(*clientStream).writeRequest(0xc000217b00, 0xc0006d7c00)
	/cilium/vendor/golang.org/x/net/http2/transport.go:1473 +0xb27
golang.org/x/net/http2.(*clientStream).doRequest(0xc000123ed0?, 0xc00009bfb8?)
	/cilium/vendor/golang.org/x/net/http2/transport.go:1335 +0x1e
created by golang.org/x/net/http2.(*ClientConn).RoundTrip
	/cilium/vendor/golang.org/x/net/http2/transport.go:1229 +0x33f

goroutine 49 [runnable]:
k8s.io/apimachinery/pkg/runtime.(*Scheme).AddUnversionedTypes(0xc0003ace00, {{0x0?, 0x14?}, {0x2c54cf2?, 0xa?}}, {0xc000609c00?, 0x5, 0x5?})
	/cilium/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:129 +0x27e
k8s.io/apimachinery/pkg/apis/meta/v1.AddToGroupVersion(0xc0003ace00?, {{0x2c9b144?, 0x0?}, {0x2c54cf2?, 0x234af00?}})
	/cilium/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/register.go:75 +0x339
k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1.addKnownTypes(0x0?)
	/cilium/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/register.go:53 +0x105
k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(...)
	/cilium/vendor/k8s.io/apimachinery/pkg/runtime/scheme_builder.go:29
helm.sh/helm/v3/pkg/kube.New.func1()
	/cilium/vendor/helm.sh/helm/v3/pkg/kube/client.go:89 +0x27
sync.(*Once).doSlow(0x39d8100?, 0x0?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
helm.sh/helm/v3/pkg/kube.New({0x39d93d0?, 0xc000035440?})
	/cilium/vendor/helm.sh/helm/v3/pkg/kube/client.go:88 +0x65
helm.sh/helm/v3/pkg/action.(*Configuration).Init(0xc000609ef8, {0x39d93d0?, 0xc000035440}, {0x2c71f81, 0xb}, {0x0, 0x0}, 0x36fcd48)
	/cilium/vendor/helm.sh/helm/v3/pkg/action/action.go:372 +0x79
github.com/cilium/cilium-cli/internal/helm.Get({0x39d93d0?, 0xc000035440?}, {{0x2c71f81?, 0x0?}, {0x2c5bd25?, 0x0?}})
	/cilium/internal/helm/helm.go:577 +0x9d
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).status.func8({0xc0006fac00?, 0xc000411700?})
	/cilium/status/k8s.go:548 +0x65
github.com/cilium/workerpool.(*WorkerPool).run.func1()
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:181 +0x82
created by github.com/cilium/workerpool.(*WorkerPool).run
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:178 +0x4e

goroutine 29 [runnable]:
sync.runtime_SemacquireMutex(0xc0006fa1d8?, 0x50?, 0xc0002c62d0?)
	/usr/local/go/src/runtime/sema.go:77 +0x26
sync.(*Mutex).lockSlow(0xc0003efa50)
	/usr/local/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:90
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).status.func5({0xc0006fa480?, 0xc000139f00?})
	/cilium/status/k8s.go:467 +0xb7
github.com/cilium/workerpool.(*WorkerPool).run.func1()
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:181 +0x82
created by github.com/cilium/workerpool.(*WorkerPool).run
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:178 +0x4e
```

**Comment by bimmlerd** [comment]
I've hit this (well, a very similar issue) again, in a second CI run. Possibly not as rare as I initially thought, or I'm just exceedingly unlucky. I believe we should set up a second k8s client for helm to use, so that this can't happen. Introducing synchronisation between these components seems non-trivial, but I'm not familiar with the code.

Link: https://github.com/cilium/cilium/actions/runs/5455131930/jobs/9926189795, 
Stack trace:
```
fatal error: concurrent map read and map write

goroutine 39 [running]:
k8s.io/apimachinery/pkg/runtime.(*Scheme).ObjectKinds(0xc000048380, {0x39c1270?, 0xc0009e7560})
	/cilium/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:267 +0x1ca
k8s.io/apimachinery/pkg/runtime.(*parameterCodec).EncodeParameters(0xc0004e9a00, {0x39c1270, 0xc0009e7560}, {{0x0, 0x0}, {0x2c54cf2, 0x2}})
	/cilium/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:191 +0x6e
k8s.io/client-go/rest.(*Request).SpecificallyVersionedParams(0xc000a08240, {0x39c1270?, 0xc0009e7560?}, {0x39c1590?, 0xc0004e9a00?}, {{0x0?, 0x2c11f00?}, {0x2c54cf2?, 0xc0006b7648?}})
	/cilium/vendor/k8s.io/client-go/rest/request.go:376 +0x83
k8s.io/client-go/rest.(*Request).VersionedParams(...)
	/cilium/vendor/k8s.io/client-go/rest/request.go:369
k8s.io/client-go/kubernetes/typed/core/v1.(*pods).List(0xc000171cc0, {0x39d8100, 0xc000614c90}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x2c9cbac, 0x14}, {0x0, ...}, ...})
	/cilium/vendor/k8s.io/client-go/kubernetes/typed/core/v1/pod.go:97 +0x145
github.com/cilium/cilium-cli/k8s.(*Client).ListPods(0xc000b3aca0?, {0x39d8100, 0xc000614c90}, {0x2c71f81, 0xb}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x2c9cbac, ...}, ...})
	/cilium/k8s/client.go:347 +0xac
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).podStatus(0x2834560?, {0x39d8100, 0xc000614c90}, 0xc0000268c0, {0x2c81abb, 0xf}, {0x2c9cbac?, 0x0?}, 0x0)
	/cilium/status/k8s.go:270 +0xa8
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).status.func3({0x0?, 0x0?})
	/cilium/status/k8s.go:428 +0x4c7
github.com/cilium/workerpool.(*WorkerPool).run.func1()
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:181 +0x82
created by github.com/cilium/workerpool.(*WorkerPool).run
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:178 +0x4e

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x405d9d?)
	/usr/local/go/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc0009c7980?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x4b
sync.(*Once).doSlow(0x39d8100?, 0x0?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
helm.sh/helm/v3/pkg/kube.New({0x39d93d0?, 0xc0005b9200?})
	/cilium/vendor/helm.sh/helm/v3/pkg/kube/client.go:88 +0x65
helm.sh/helm/v3/pkg/action.(*Configuration).Init(0xc0008e7ef8, {0x39d93d0?, 0xc0005b9200}, {0x2c71f81, 0xb}, {0x0, 0x0}, 0x36fcd48)
	/cilium/vendor/helm.sh/helm/v3/pkg/action/action.go:372 +0x79
github.com/cilium/cilium-cli/internal/helm.Get({0x39d93d0?, 0xc0005b9200?}, {{0x2c71f81?, 0x0?}, {0x2c5bd25?, 0x0?}})
	/cilium/internal/helm/helm.go:577 +0x9d
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).status.func8({0xc000686180?, 0xc00069a300?})
	/cilium/status/k8s.go:548 +0x65
github.com/cilium/workerpool.(*WorkerPool).run.func1()
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:181 +0x82
created by github.com/cilium/workerpool.(*WorkerPool).run
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:178 +0x4e

goroutine 42 [runnable]:
k8s.io/client-go/rest.(*Request).URL(0xc000a91560)
	/cilium/vendor/k8s.io/client-go/rest/request.go:511 +0x38e
k8s.io/client-go/rest.(*Request).tryThrottleWithInfo(0xc000a91560, {0x39d8100, 0xc000614c90}, {0x0, 0x0})
	/cilium/vendor/k8s.io/client-go/rest/request.go:624 +0x272
k8s.io/client-go/rest.(*Request).tryThrottle(...)
	/cilium/vendor/k8s.io/client-go/rest/request.go:641
k8s.io/client-go/rest.(*Request).request(0xc000a91560, {0x39d8100, 0xc000614c90}, 0x2?)
	/cilium/vendor/k8s.io/client-go/rest/request.go:965 +0x21b
k8s.io/client-go/rest.(*Request).Do(0xc000a91560, {0x39d8100, 0xc000614c90})
	/cilium/vendor/k8s.io/client-go/rest/request.go:1039 +0xc9
k8s.io/client-go/kubernetes/typed/core/v1.(*pods).List(0xc00008a7c0, {0x39d8100, 0xc000614c90}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}, {0x0, ...}, ...})
	/cilium/vendor/k8s.io/client-go/kubernetes/typed/core/v1/pod.go:99 +0x170
github.com/cilium/cilium-cli/k8s.(*Client).ListPods(0xc0004ee200?, {0x39d8100, 0xc000614c90}, {0x0, 0x0}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, ...}, ...})
	/cilium/k8s/client.go:347 +0xac
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).podCount(0xc000026850, {0x39d8100, 0xc000614c90}, 0xc0000268c0)
	/cilium/status/k8s.go:191 +0x7c
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).status.func7({0xc000686300?, 0xc00069a600?})
	/cilium/status/k8s.go:527 +0x5a
github.com/cilium/workerpool.(*WorkerPool).run.func1()
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:181 +0x82
created by github.com/cilium/workerpool.(*WorkerPool).run
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:178 +0x4e

goroutine 52 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0xc000614c90?)
	/usr/local/go/src/runtime/sema.go:77 +0x26
sync.(*Mutex).lockSlow(0xc0002772d0)
	/usr/local/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:90
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).status.func6({0xc000aac000?, 0xc000aa6200?})
	/cilium/status/k8s.go:498 +0xb7
github.com/cilium/workerpool.(*WorkerPool).run.func1()
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:181 +0x82
created by github.com/cilium/workerpool.(*WorkerPool).run
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:178 +0x4e
```

**Comment by tommyp1ckles** [comment]
Just hit this here as well: https://github.com/cilium/cilium/actions/runs/5472243546/jobs/9964213169?pr=26583

**Comment by tklauser** [comment]
Saw this issue again on https://github.com/cilium/cilium/pull/26800(https://github.com/cilium/cilium/actions/runs/5541124605/jobs/10114250971#step:15:22) with cilium-cli v0.15.2 which has #1802 in place. Looks like this is not completely fixed :cry: Reopening.
