### ISSUE TITLE
cilium status --wait v0.15.2 causes fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by aanm** [cilium/cilium-cli#1831]
```
fatal error: concurrent map read and map write

goroutine 49 [running]:
k8s.io/apimachinery/pkg/runtime.(*Scheme).ObjectKinds(0xc000343f80, {0x39e2bd8?, 0xc000adc090})
	/cilium/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:267 +0x1ca
k8s.io/apimachinery/pkg/runtime.(*parameterCodec).EncodeParameters(0xc0003fd7c0, {0x39e2bd8, 0xc000adc090}, {{0x0, 0x0}, {0x2c4ceb2, 0x2}})
	/cilium/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:191 +0x6e
k8s.io/client-go/rest.(*Request).SpecificallyVersionedParams(0xc000557e60, {0x39e2bd8?, 0xc000adc090?}, {0x39e2ef8?, 0xc0003fd7c0?}, {{0x0?, 0x0?}, {0x2c4ceb2?, 0xc000a938e0?}})
	/cilium/vendor/k8s.io/client-go/rest/request.go:376 +0x83
k8s.io/client-go/rest.(*Request).VersionedParams(...)
	/cilium/vendor/k8s.io/client-go/rest/request.go:369
k8s.io/client-go/kubernetes/typed/core/v1.(*pods).List(0xc000164c00, {0x39f9aa0, 0xc00066cb70}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}, {0x0, ...}, ...})
	/cilium/vendor/k8s.io/client-go/kubernetes/typed/core/v1/pod.go:97 +0x145
github.com/cilium/cilium-cli/k8s.(*Client).ListPods(0x0?, {0x39f9aa0, 0xc00066cb70}, {0x0, 0x0}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, ...}, ...})
	/cilium/k8s/client.go:359 +0xac
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).podCount(0xc000270070, {0x39f9aa0, 0xc00066cb70}, 0xc0002700e0)
	/cilium/status/k8s.go:191 +0x7c
github.com/cilium/cilium-cli/status.(*K8sStatusCollector).status.func7({0x0?, 0x0?})
	/cilium/status/k8s.go:527 +0x5a
github.com/cilium/workerpool.(*WorkerPool).run.func1()
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:181 +0x82
created by github.com/cilium/workerpool.(*WorkerPool).run
	/cilium/vendor/github.com/cilium/workerpool/workerpool.go:178 +0x4e

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x405d9d?)
	/usr/local/go/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc000a47980?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x4b
net.(*conn).Read(0xc00011a500, {0xc0009d4000?, 0xc0009d5e42?, 0x5?})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0001143d8, {0xc0009d4000?, 0xc0001143d8?, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc000676290, {0x39c4100, 0xc0001143d8})
	/usr/local/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000676000, {0x7f3c88c40998?, 0xc00066a000}, 0x51be?)
	/usr/local/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc000676000, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc000676000, {0xc00077f000, 0x1000, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:1316 +0x16f
bufio.(*Reader).Read(0xc00077a2a0, {0xc00076e200, 0x9, 0xc0008bb288?})
	/usr/local/go/src/bufio/bufio.go:237 +0x1bb
io.ReadAtLeast({0x39c3e40, 0xc00077a2a0}, {0xc00076e200, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:351
golang.org/x/net/http2.readFrameHeader({0xc00076e200?, 0x9?, 0xc00166d3b0?}, {0x39c3e40?, 0xc00077a2a0?})
	/cilium/vendor/golang.org/x/net/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00076e1c0)
	/cilium/vendor/golang.org/x/net/http2/frame.go:498 +0x95
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000672f98)
	/cilium/vendor/golang.org/x/net/http2/transport.go:[22](https://github.com/cilium/cilium/actions/runs/5541721342/jobs/10115505363#step:15:23)60 +0x12e
golang.org/x/net/http2.(*ClientConn).readLoop(0xc0008ba900)
	/cilium/vendor/golang.org/x/net/http2/transport.go:2[155](https://github.com/cilium/cilium/actions/runs/5541721342/jobs/10115505363#step:15:156) +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/cilium/vendor/golang.org/x/net/http2/transport.go:818 +0xc1f
```

**Comment by aanm** [comment]
seen in https://github.com/cilium/cilium/actions/runs/5541721342/attempts/1

**Comment by tklauser** [comment]
Looks like a reoccurrence of #1794

**Comment by michi-covalent** [comment]
i'm working on fixing this. let's use #1794 for tracking. closing this issue as a duplicate ✅
