### ISSUE TITLE
Bugtool output truncated or absent from sysdump

### ISSUE THREAD

**Issue by bmcustodio** [cilium/cilium-cli#616]
Sometimes sysdumps will be either entirely missing a given `cilium-bugtool-*` tar file, or contain an incomplete one. It's unclear if this is the same issue or two different ones, but one of them has been observed to be caused by an `unexpected EOF` error that also happens during `kubectl cp` (which is the same mechanism used to transfer the bugtool tar from the Cilium pods to the local machine):

```
I1118 16:22:32.676181   48429 connection.go:198] SPDY Ping failed: connection closed
F1118 16:22:32.676629   48429 helpers.go:116] error: unexpected EOF
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00013c001, 0xc0005a4640, 0x44, 0x91)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x6e0d540, 0xc000000003, 0x0, 0x0, 0xc0004f4310, 0x2, 0x64e8137, 0xa, 0x74, 0x400ff00)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x1e5
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x6e0d540, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc000712060, 0x1, 0x1)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:735 +0x185
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1500
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal(0xc000cb40a8, 0x15, 0x1)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:94 +0x288
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x5f2b1c0, 0xc000122070, 0x5da0428)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:189 +0x935
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:116
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/cp.NewCmdCp.func2(0xc000798c80, 0xc0001844b0, 0x2, 0x5)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/cp/cp.go:153 +0xec
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000798c80, 0xc000184460, 0x5, 0x5, 0xc000798c80, 0xc000184460)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000148780, 0xc00013e120, 0xc000140000, 0x7)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:960 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:897
main.main()
        _output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d

goroutine 19 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x6e0d540)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:420 +0xdf

goroutine 5 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x5da0330, 0x5f2d160, 0xc0005b2000, 0x1, 0xc000118b40)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x118
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x5da0330, 0x12a05f200, 0x0, 0x1, 0xc000118b40)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x5da0330, 0x12a05f200, 0xc000118b40)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96

goroutine 24 [IO wait]:
internal/poll.runtime_pollWait(0xf39d498, 0x72, 0xffffffffffffffff)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc00083c118, 0x72, 0x5a00, 0x5a98, 0xffffffffffffffff)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00083c100, 0xc000904000, 0x5a98, 0x5a98, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc00083c100, 0xc000904000, 0x5a98, 0x5a98, 0x2902, 0xc000907191, 0x5)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000186010, 0xc000904000, 0x5a98, 0x5a98, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc00073c798, 0xc000904000, 0x5a98, 0x5a98, 0x2902, 0xc000600000, 0x0)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc00003e978, 0x5f2afc0, 0xc00073c798, 0x400d4a5, 0x58d16a0, 0x5a9c3c0)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc00003e700, 0x7f75a58, 0xc000186010, 0x5, 0xc000186010, 0x9)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc00003e700, 0x0, 0x0, 0xc000010010)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc00003e700, 0xc00058a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/crypto/tls/conn.go:1276 +0x165
bufio.(*Reader).Read(0xc0003791a0, 0xc0005741f8, 0x9, 0x9, 0x45a94eb, 0xc000835c78, 0x4008b05)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x5f2adc0, 0xc0003791a0, 0xc0005741f8, 0x9, 0x9, 0x9, 0xc0006138c0, 0xdedb0704222200, 0xc0006138c0)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/io/io.go:328 +0x87
io.ReadFull(...)
        /usr/local/Cellar/go@1.16/1.16.10/libexec/src/io/io.go:347
k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader(0xc0005741f8, 0x9, 0x9, 0x5f2adc0, 0xc0003791a0, 0x0, 0xc000000000, 0x405ab85, 0x4073b20)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x89
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0005741c0, 0xc0004aab40, 0x0, 0x0, 0x0)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000835fa8, 0x0, 0x0)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1821 +0xd8
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc000188f00)
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1743 +0x6f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
        /private/tmp/kubernetes-cli-20211118-19721-pemzfc/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:695 +0x6c5
```

I'm not entirely sure what the proper fix is, but I think we can at least try to improve the robustness of the copying process by retrying until we don't get the `EOF` error or a given number of attempts is exceeded.

**Comment by gandro** [comment]
From #654 

> For large bugtool output files downloading the file via `kubectl exec cat` seems to fail on some K8s apiserver instances:
> 
> ```
> ⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-agent-tl2s9": reading file in tar archive: /redacted/cilium-sysdump-20211209-173133/cilium-bugtool-cilium-agent-abcde-20211209-173040/cmd/cilium-bpf-ct-list-global.md: writing file: unexpected EOF
> ```
> 
> The file was correctly created on the pod, and could be downloaded manually.
> 
> Instead of `cat`ing very large files, we should probably try to split the file into smaller chunks and download them individually (including potentially adding a retry logic). Legacy sysdump (which uses `kubectl cp`) also failed in this particular instance.

**Comment by gandro** [comment]
Another additional mitigation would be to gzip the bugtool output. It seems to reduce the tar archive ~9x.

**Comment by sayboras** [comment]
> Another additional mitigation would be to gzip the bugtool output. It seems to reduce the tar archive ~9x.

 I feel bugtool should support .tar.gz directly, currently bugtool only allows .tar or .gz. I can make changes in cilium repo, and then iwe can just upgrade bugtool in cilium-cli repo.

**Comment by gandro** [comment]
> Updated: Looking at the code in both cilium and cilium-cli, the above is not ideal as cilium installation will be lagged behind, so cilium-cli should not assume bugtool version i.e. GZ compression should be done in cilium-cli repo.

Yes, agreed. We should teach the bugtool about .tar.gz, but we should also find a mechanism that improves the mechanism for older versions of Cilium too.

**Comment by sayboras** [comment]
Fixed as part of https://github.com/cilium/cilium-cli/pull/671. I am closing this issue, we can re-open if it is still happening.
